# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-01 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_boiler',
            field=models.ManyToManyField(to='todo.TypeBoiler'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 1, 21, 25, 55, 514511, tzinfo=utc), null=True, verbose_name='Кінцева дата'),
        ),
    ]
