# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-02 11:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_auto_20200601_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 2, 11, 10, 16, 192871, tzinfo=utc), null=True, verbose_name='Кінцева дата'),
        ),
        migrations.AddField(
            model_name='review',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Todo'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
